ThereIsHope/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('hope.urls')),
    path('admins/', include('admins.urls')),
    path('admin/', admin.site.urls),
]

hope/urls.py
from django.contrib import admin
from django.urls import path
from . import views as v

app_name = 'hope'

urlpatterns = [
    path('', v.index, name='index'),
    path('about', v.about_view, name='about'),
    path('view/<slug:slug>', v.blog_view, name='view'),
    path('contactMessage', v.contact_view, name='message'),
    path('activities', v.activities_view, name='activities'),
    path('portfolios', v.portfolio_view, name='portfolios'),
    path('about-me', v.about_me, name='about_me'),
    path('donate', v.donation_view, name='donation'),
]

hope/models.py
from django.db import models
from django.utils.text import slugify

class Contact(models.Model):
    name        = models.CharField(max_length=255)
    email       = models.EmailField(max_length=254)
    subject     = models.CharField(max_length=50)
    message     = models.TextField()
    slug        = models.SlugField(max_length=140, unique=True, blank=True)
    date        = models.DateTimeField(blank=True, auto_now_add=True, null=True)

    def __str__(self):
        return self.subject

    def get_unique_slug(self):
        slug = slugify(self.subject)  
        unique_slug = slug

        num = 1
        while Contact.objects.filter(slug=unique_slug).exists():
            unique_slug = '{}-{}'.format(slug, num)

            num += 1

        return unique_slug


    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = self.get_unique_slug()
        super().save(*args, **kwargs)


class Portfolio(models.Model):
    HOSP    =  'hospital'
    ORPH   =  'orphanage'
    PRIS     =  'prisons'
    DRU =  'drug_addiction'

    CATEGORY_SELECT = [
        (HOSP, 'Hospital'),
        (ORPH, 'Orphanage'),
        (PRIS, 'Prisons'),
        (DRU, 'Drug addiction center')
    ]
    

    title           =   models.CharField(max_length=225)
    description     =   models.TextField()
    category        =   models.CharField(choices=CATEGORY_SELECT, max_length=20)
    date            =   models.DateField(auto_now_add=True)
    img_url         =   models.URLField(max_length=2000)
    slug            =   models.SlugField(max_length=140, unique=True, blank=True)


    def __str__(self):
        return self.title
    
    def get_unique_slug(self):
        slug    =   slugify(self.title)
        unigue_slug =   slug

        num = 1
        while Portfolio.objects.filter(slug=unigue_slug).exists():
            unigue_slug = '{}_{}'.format(slug, num)

            num += 1

        return unigue_slug


    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = self.get_unique_slug()
        super().save(*args, **kwargs)       

        

hope/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Contact, Portfolio

# Create your views here.
def index(request):
    portfolios = Portfolio.objects.all().order_by('-id')[:9]
    return render(request, 'hope/pages/index.html', {'portfolios': portfolios})
    
def about_view(request):
    portfolio = Portfolio.objects.all()
    return render(request, 'hope/pages/blog/about.html', {'portfolio':portfolio})    

def blog_view(request, slug):
    portfolio = Portfolio.objects.get(slug=slug)
    related = Portfolio.objects.exclude(slug=slug)[:4]
    return render(request, 'hope/pages/blog/blog.html', {'portfolio': portfolio, 'related': related})

def contact_view(request):
    if request.method == 'POST':
        name = request.POST['name']
        email = request.POST['email']
        subject = request.POST['subject']
        message = request.POST['message']

        contact = Contact(name=name, email=email, subject=subject, message=message)
        contact.save()

        return HttpResponse("OK")


def portfolio_view(request):
    portfolio = Portfolio.objects.all()
    return render(request, 'hope/pages/blog/allPortfolios.html', {'portfolio': portfolio})        


def about_me(request):
    return render(request, 'hope/pages/aboutMe.html')
    
def activities_view(request):
    return render(request, 'hope/pages/activitiesPage.html')
    
def donation_view(request):

    return render(request, 'hope/pages/donation.html')    

hope/templates/hope/pages/indexComponents/activities.html
<section id="activities">
    <div class="container">

        <header class="section-header wow fadeInUp">
            <h3>Our Activities</h3>
            <p>We ought to see that, those people with less privilege in the societies are remembered and their hope is restored back.</p>
        </header>

        <div class="row">

            <div class="col-lg-4 col-md-6 box wow bounceInUp" data-wow-duration="1.4s">
                <div class="icon"><i class="ion-ios-analytics-outline"></i></div>
                <h4 class="title"><a href="{% url 'hope:activities' %}#first">VISITING THE ORPHAGE CENTERS</a></h4>
                <p class="description">The intention of visiting these centers is to relieve sufferings and necessities of orphans by supplying their needs but also to socialize with them...</p>
            </div>
            <div class="col-lg-4 col-md-6 box wow bounceInUp" data-wow-duration="1.4s">
                <div class="icon"><i class="ion-ios-bookmarks-outline"></i></div>
                <h4 class="title"><a href="{% url 'hope:activities' %}#1">COMFORTING PATIENTS FROM DIFFERENT HOSPITALS</a></h4>
                <p class="description">Nevertheless, that we are providing physical needs to those who are sick, but a tender visit and comfort in their chronic illness accompanied with...</p>
            </div>
            <div class="col-lg-4 col-md-6 box wow bounceInUp" data-wow-duration="1.4s">
                <div class="icon"><i class="ion-ios-paper-outline"></i></div>
                <h4 class="title"><a href="{% url 'hope:activities' %}#2">TO VISIT PRISONERS</a></h4>
                <p class="description">Another step that is crucial is to comfort the prisoners, helping them with their basic needs, distributing to them books that will help them to...</p>
            </div>
            <div class="col-lg-4 col-md-6 box wow bounceInUp" data-wow-delay="0.1s" data-wow-duration="1.4s">
                <div class="icon"><i class="ion-ios-speedometer-outline"></i></div>
                <h4 class="title"><a href="{% url 'hope:activities' %}#3">SUPPORTING ELDERLY PEOPLE</a></h4>
                <p class="description">Many elderly individuals suffer from loneliness, neglect and psychological distress due to their dependence, as the team we have to take serious...</p>
            </div>
            <div class="col-lg-4 col-md-6 box wow bounceInUp" data-wow-delay="0.1s" data-wow-duration="1.4s">
                <div class="icon"><i class="ion-ios-barcode-outline"></i></div>
                <h4 class="title"><a href="{% url 'hope:activities' %}#4">VISITING SCHOOLS AND IMPACTING YOUTHS LIFE</a></h4>
                <p class="description">Through motivations, and providing good presentations that will enlights the mind of many youth will bring a great impact upon many students...</p>
            </div>
            <div class="col-lg-4 col-md-6 box wow bounceInUp" data-wow-delay="0.1s" data-wow-duration="1.4s">
                <div class="icon"><i class="ion-ios-people-outline"></i></div>
                <h4 class="title"><a href="{% url 'hope:activities' %}#5">CONDUCTING HEALTH SEMINORS</a></h4>
                <p class="description">Prevention is better than cure. We will join hands together with other members of health professions to create an education platform on health...</p>
            </div>

        </div>

    </div>
</section>

hope/templates/hope/pages/indexComponents/contact.html
<section id="contact" class="section-bg wow fadeInUp">
    <div class="container">

        <div class="section-header">
            <h3>Contact Us</h3>
            <p>Reach us at anytime</p>
        </div>

        <div class="row contact-info">

            <div class="col-md-4">
                <div class="contact-address">
                    <i class="ion-ios-location-outline"></i>
                    <h3>Address</h3>
                    <address>Mikocheni, DSM Tanzania</address>
                </div>
            </div>

            <div class="col-md-4">
                <div class="contact-phone">
                    <i class="ion-ios-telephone-outline"></i>
                    <h3>Phone Number</h3>
                    <p><a href="tel:+255752518474">+255 752 518 474</a></p>
                </div>
            </div>

            <div class="col-md-4">
                <div class="contact-email">
                    <i class="ion-ios-email-outline"></i>
                    <h3>Email</h3>
                    <p><a href="mailto:victorjumanne1997@gmail.com">victorjumanne1997@gmail.com</a></p>
                </div>
            </div>

        </div>

        <div class="form">
            <div id="sendmessage">Your message has been sent. Thank you!</div>
            <div id="errormessage"></div>
            <form action="{% url 'hope:message' %}" method="post" role="form" class="contactForm">
                {% csrf_token %}
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <input type="text" name="name" class="form-control" id="name" placeholder="Your Name" data-rule="minlen:4" data-msg="Please enter at least 4 chars" />
                        <div class="validation"></div>
                    </div>
                    <div class="form-group col-md-6">
                        <input type="email" class="form-control" name="email" id="email" placeholder="Your Email" data-rule="email" data-msg="Please enter a valid email" />
                        <div class="validation"></div>
                    </div>
                </div>
                <div class="form-group">
                    <input type="text" class="form-control" name="subject" id="subject" placeholder="Subject" data-rule="minlen:4" data-msg="Please enter at least 8 chars of subject" />
                    <div class="validation"></div>
                </div>
                <div class="form-group">
                    <textarea class="form-control" name="message" rows="5" data-rule="required" data-msg="Please write something for us" placeholder="Message"></textarea>
                    <div class="validation"></div>
                </div>
                <div class="text-center"><button type="submit">Send Message</button></div>
            </form>
        </div>

    </div>
</section>

hope/templates/hope/pages/indexComponents/potfolio.html
{% load static %}
<section id="portfolio" class="section-bg">
    <div class="container">

        <header class="section-header">
            <h3 class="section-title">Our Portfolio</h3>
        </header>

        <div class="row">
            <div class="col-lg-12">
                <ul id="portfolio-flters">
                    <li data-filter="*" class="filter-active">All</li>
                    <li data-filter=".filter-hospital">Hospital</li>
                    <li data-filter=".filter-prisons">Prisons</li>
                    <li data-filter=".filter-orphanage">Orphanage</li>
                    <li data-filter=".filter-drug_addiction">Drug Addiction</li>
                    <li class="port"><a href="{% url 'hope:portfolios' %}#title">View all</a></li>
                </ul>
            </div>
        </div>

        <div class="row portfolio-container">
            {% for portfolio in portfolios %} {% if portfolio.category == 'hospital' %}
            <div class="col-lg-4 col-md-6 portfolio-item filter-hospital wow fadeInUp">
                <div class="portfolio-wrap">
                    <figure>
                        <img src="{{ portfolio.img_url }}#{{portfolio.id}}" class="img-fluid" alt="">
                        <a href="{{ portfolio.img_url }}" data-lightbox="portfolio" data-title="{{ portfolio.title }}" class="link-preview" title="Preview"><i class="ion ion-eye"></i></a>
                        <a href="{% url 'hope:view' portfolio.slug %}#{{portfolio.id}}" class="link-details" title="More Details"><i class="ion ion-android-open"></i></a>
                    </figure>

                    <div class="portfolio-info">
                        <h4><a href="{% url 'hope:view' portfolio.slug %}#{{portfolio.id}}">{{ portfolio.title }}</a></h4>
                        <p>{{ portfolio.category }}</p>
                    </div>
                </div>
            </div>
            {% elif portfolio.category == 'prisons' %}
            <div class="col-lg-4 col-md-6 portfolio-item filter-prisons wow fadeInUp" data-wow-delay="0.1s">
                <div class="portfolio-wrap">
                    <figure>
                        <img src="{{ portfolio.img_url }}#{{portfolio.id}}" class="img-fluid" alt="">
                        <a href="{{ portfolio.img_url }}" class="link-preview" data-lightbox="portfolio" data-title="{{ portfolio.title }}" title="Preview"><i class="ion ion-eye"></i></a>
                        <a href="{% url 'hope:view' portfolio.slug %}#{{portfolio.id}}" class="link-details" title="More Details"><i class="ion ion-android-open"></i></a>
                    </figure>

                    <div class="portfolio-info">
                        <h4><a href="{% url 'hope:view' portfolio.slug %}#{{portfolio.id}}">{{ portfolio.title }}</a></h4>
                        <p>{{ portfolio.category }}</p>
                    </div>
                </div>
            </div>
            {% elif portfolio.category == 'orphanage' %}
            <div class="col-lg-4 col-md-6 portfolio-item filter-orphanage wow fadeInUp" data-wow-delay="0.1s">
                <div class="portfolio-wrap">
                    <figure>
                        <img src="{{ portfolio.img_url }}#{{portfolio.id}}" class="img-fluid" alt="">
                        <a href="{{ portfolio.img_url }}" class="link-preview" data-lightbox="portfolio" data-title="{{ portfolio.title }}" title="Preview"><i class="ion ion-eye"></i></a>
                        <a href="{% url 'hope:view' portfolio.slug %}#{{portfolio.id}}" class="link-details" title="More Details"><i class="ion ion-android-open"></i></a>
                    </figure>

                    <div class="portfolio-info">
                        <h4><a href="{% url 'hope:view' portfolio.slug %}#{{portfolio.id}}">{{ portfolio.title }}</a></h4>
                        <p>{{ portfolio.category }}</p>
                    </div>
                </div>
            </div>
            {% elif portfolio.category == 'drug_addiction' %}
            <div class="col-lg-4 col-md-6 portfolio-item filter-drug_addiction wow fadeInUp" data-wow-delay="0.1s">
                <div class="portfolio-wrap">
                    <figure>
                        <img src="{{ portfolio.img_url }}#{{portfolio.id}}" class="img-fluid" alt="">
                        <a href="{{ portfolio.img_url }}" class="link-preview" data-lightbox="portfolio" data-title="{{ portfolio.title }}" title="Preview"><i class="ion ion-eye"></i></a>
                        <a href="{% url 'hope:view' portfolio.slug %}#{{portfolio.id}}" class="link-details" title="More Details"><i class="ion ion-android-open"></i></a>
                    </figure>

                    <div class="portfolio-info">
                        <h4><a href="{% url 'hope:view' portfolio.slug %}#{{portfolio.id}}">{{ portfolio.title }}</a></h4>
                        <p>{{ portfolio.category }}</p>
                    </div>
                </div>
            </div>
            {% endif %} {% endfor %}

        </div>

    </div>
</section>

hope/templates/hope/pages/indexComponents/team.html
{% load static %}
<section class="testemonial">
    <div class="container">

        <div class="gallary-header text-center">
            <h2>
                our team
            </h2>
            <p>
                Duis aute irure dolor in velit esse cillum dolore eu fugiat nulla.
            </p>

        </div>
        <!--/.gallery-header-->

        <div class="owl-carousel owl-theme" id="testemonial-carousel">

            <div class="home1-testm item">
                <div class="home1-testm-single text-center">
                    <div class="home1-testm-img">
                        <img src="{% static 'assets/images/client/testimonial1.jpg' %}" alt="img" />
                    </div>
                    <!--/.home1-testm-img-->
                    <div class="home1-testm-txt">
                        <span class="icon section-icon">
                            <i class="fa fa-quote-left" aria-hidden="true"></i>
                        </span>
                        <p>
                            Lorem ipsum dolor sit amet, contur adip elit, sed do mod incid ut labore et dolore magna aliqua. Ut enim ad minim veniam.
                        </p>
                        <h3>
                            <a href="#">
                                kevin watson
                            </a>
                        </h3>
                        <h4>london, england</h4>
                    </div>
                    <!--/.home1-testm-txt-->
                </div>
                <!--/.home1-testm-single-->

            </div>
            <!--/.item-->

            <div class="home1-testm item">
                <div class="home1-testm-single text-center">
                    <div class="home1-testm-img">
                        <img src="{% static 'assets/images/client/testimonial2.jpg' %}" alt="img" />
                    </div>
                    <!--/.home1-testm-img-->
                    <div class="home1-testm-txt">
                        <span class="icon section-icon">
                            <i class="fa fa-quote-left" aria-hidden="true"></i>
                        </span>
                        <p>
                            Lorem ipsum dolor sit amet, contur adip elit, sed do mod incid ut labore et dolore magna aliqua. Ut enim ad minim veniam.
                        </p>
                        <h3>
                            <a href="#">
                                kevin watson
                            </a>
                        </h3>
                        <h4>london, england</h4>
                    </div>
                    <!--/.home1-testm-txt-->
                </div>
                <!--/.home1-testm-single-->

            </div>
            <!--/.item-->

            <div class="home1-testm item">
                <div class="home1-testm-single text-center">
                    <div class="home1-testm-img">
                        <img src="{% static 'assets/images/client/testimonial1.jpg' %}" alt="img" />
                    </div>
                    <!--/.home1-testm-img-->
                    <div class="home1-testm-txt">
                        <span class="icon section-icon">
                            <i class="fa fa-quote-left" aria-hidden="true"></i>
                        </span>
                        <p>
                            Lorem ipsum dolor sit amet, contur adip elit, sed do mod incid ut labore et dolore magna aliqua. Ut enim ad minim veniam.
                        </p>
                        <h3>
                            <a href="#">
                                kevin watson
                            </a>
                        </h3>
                        <h4>london, england</h4>
                    </div>
                    <!--/.home1-testm-txt-->
                </div>
                <!--/.home1-testm-single-->

            </div>
            <!--/.item-->

            <div class="home1-testm item">
                <div class="home1-testm-single text-center">
                    <div class="home1-testm-img">
                        <img src="{% static 'assets/images/client/testimonial1.jpg' %}" alt="img" />
                    </div>
                    <!--/.home1-testm-img-->
                    <div class="home1-testm-txt">
                        <span class="icon section-icon">
                            <i class="fa fa-quote-left" aria-hidden="true"></i>
                        </span>
                        <p>
                            Lorem ipsum dolor sit amet, contur adip elit, sed do mod incid ut labore et dolore magna aliqua. Ut enim ad minim veniam.
                        </p>
                        <h3>
                            <a href="#">
                                kevin watson
                            </a>
                        </h3>
                        <h4>london, england</h4>
                    </div>
                    <!--/.home1-testm-txt-->
                </div>
                <!--/.home1-testm-single-->

            </div>
            <!--/.item-->

            <div class="home1-testm item">
                <div class="home1-testm-single text-center">
                    <div class="home1-testm-img">
                        <img src="{% static 'assets/images/client/testimonial2.jpg' %}" alt="img" />
                    </div>
                    <!--/.home1-testm-img-->
                    <div class="home1-testm-txt">
                        <span class="icon section-icon">
                            <i class="fa fa-quote-left" aria-hidden="true"></i>
                        </span>
                        <p>
                            Lorem ipsum dolor sit amet, contur adip elit, sed do mod incid ut labore et dolore magna aliqua. Ut enim ad minim veniam.
                        </p>
                        <h3>
                            <a href="#">
                                kevin watson
                            </a>
                        </h3>
                        <h4>london, england</h4>
                    </div>
                    <!--/.home1-testm-txt-->
                </div>
                <!--/.home1-testm-single-->

            </div>
            <!--/.item-->

            <div class="home1-testm item">
                <div class="home1-testm-single text-center">
                    <div class="home1-testm-img">
                        <img src="{% static 'assets/images/client/testimonial1.jpg' %}" alt="img" />
                    </div>
                    <!--/.home1-testm-img-->
                    <div class="home1-testm-txt">
                        <span class="icon section-icon">
                            <i class="fa fa-quote-left" aria-hidden="true"></i>
                        </span>
                        <p>
                            Lorem ipsum dolor sit amet, contur adip elit, sed do mod incid ut labore et dolore magna aliqua. Ut enim ad minim veniam.
                        </p>
                        <h3>
                            <a href="#">
                                kevin watson
                            </a>
                        </h3>
                        <h4>london, england</h4>
                    </div>
                    <!--/.home1-testm-txt-->
                </div>
                <!--/.home1-testm-single-->

            </div>
            <!--/.item-->

            <div class="home1-testm item">
                <div class="home1-testm-single text-center">
                    <div class="home1-testm-img">
                        <img src="{% static 'assets/images/client/testimonial1.jpg' %}" alt="img" />
                    </div>
                    <!--/.home1-testm-img-->
                    <div class="home1-testm-txt">
                        <span class="icon section-icon">
                            <i class="fa fa-quote-left" aria-hidden="true"></i>
                        </span>
                        <p>
                            Lorem ipsum dolor sit amet, contur adip elit, sed do mod incid ut labore et dolore magna aliqua. Ut enim ad minim veniam.
                        </p>
                        <h3>
                            <a href="#">
                                kevin watson
                            </a>
                        </h3>
                        <h4>london, england</h4>
                    </div>
                    <!--/.home1-testm-txt-->
                </div>
                <!--/.home1-testm-single-->

            </div>
            <!--/.item-->

            <div class="home1-testm item">
                <div class="home1-testm-single text-center">
                    <div class="home1-testm-img">
                        <img src="{% static 'assets/images/client/testimonial2.jpg" alt="img" />
                    </div>
                    <!--/.home1-testm-img-->
                    <div class="home1-testm-txt">
                        <span class="icon section-icon">
                            <i class="fa fa-quote-left" aria-hidden="true"></i>
                        </span>
                        <p>
                            Lorem ipsum dolor sit amet, contur adip elit, sed do mod incid ut labore et dolore magna aliqua. Ut enim ad minim veniam.
                        </p>
                        <h3>
                            <a href="#">
                                kevin watson
                            </a>
                        </h3>
                        <h4>london, england</h4>
                    </div>
                    <!--/.home1-testm-txt-->
                </div>
                <!--/.home1-testm-single-->

            </div>
            <!--/.item-->

            <div class="home1-testm item">
                <div class="home1-testm-single text-center">
                    <div class="home1-testm-img">
                        <img src="assets/images/client/testimonial1.jpg" alt="img" />
                    </div>
                    <!--/.home1-testm-img-->
                    <div class="home1-testm-txt">
                        <span class="icon section-icon">
                            <i class="fa fa-quote-left" aria-hidden="true"></i>
                        </span>
                        <p>
                            Lorem ipsum dolor sit amet, contur adip elit, sed do mod incid ut labore et dolore magna aliqua. Ut enim ad minim veniam.
                        </p>
                        <h3>
                            <a href="#">
                                kevin watson
                            </a>
                        </h3>
                        <h4>london, england</h4>
                    </div>
                    <!--/.home1-testm-txt-->
                </div>
                <!--/.home1-testm-single-->

            </div>
            <!--/.item-->

        </div>
        <!--/.testemonial-carousel-->
    </div>
    <!--/.container-->

</section>