ThereIsHope/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('hope.urls')),
    path('admins/', include('admins.urls')),
    path('admin/', admin.site.urls),
]

hope/urls.py
from django.contrib import admin
from django.urls import path
from . import views as v

app_name = 'hope'

urlpatterns = [
    path('', v.index, name='index'),
    path('about', v.about_view, name='about'),
    path('view/<slug:slug>', v.blog_view, name='view'),
    path('contactMessage', v.contact_view, name='message'),
    path('activities', v.activities_view, name='activities'),
    path('portfolios', v.portfolio_view, name='portfolios'),
    path('about-me', v.about_me, name='about_me'),
    path('donate', v.donation_view, name='donation'),
]

hope/models.py
from django.db import models
from django.utils.text import slugify

class Contact(models.Model):
    name        = models.CharField(max_length=255)
    email       = models.EmailField(max_length=254)
    subject     = models.CharField(max_length=50)
    message     = models.TextField()
    slug        = models.SlugField(max_length=140, unique=True, blank=True)
    date        = models.DateTimeField(blank=True, auto_now_add=True, null=True)

    def __str__(self):
        return self.subject

    def get_unique_slug(self):
        slug = slugify(self.subject)  
        unique_slug = slug

        num = 1
        while Contact.objects.filter(slug=unique_slug).exists():
            unique_slug = '{}-{}'.format(slug, num)

            num += 1

        return unique_slug


    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = self.get_unique_slug()
        super().save(*args, **kwargs)


class Portfolio(models.Model):
    HOSP    =  'hospital'
    ORPH   =  'orphanage'
    PRIS     =  'prisons'
    DRU =  'drug_addiction'

    CATEGORY_SELECT = [
        (HOSP, 'Hospital'),
        (ORPH, 'Orphanage'),
        (PRIS, 'Prisons'),
        (DRU, 'Drug addiction center')
    ]
    

    title           =   models.CharField(max_length=225)
    description     =   models.TextField()
    category        =   models.CharField(choices=CATEGORY_SELECT, max_length=20)
    date            =   models.DateField(auto_now_add=True)
    img_url         =   models.URLField(max_length=2000)
    slug            =   models.SlugField(max_length=140, unique=True, blank=True)


    def __str__(self):
        return self.title
    
    def get_unique_slug(self):
        slug    =   slugify(self.title)
        unigue_slug =   slug

        num = 1
        while Portfolio.objects.filter(slug=unigue_slug).exists():
            unigue_slug = '{}_{}'.format(slug, num)

            num += 1

        return unigue_slug


    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = self.get_unique_slug()
        super().save(*args, **kwargs)       

        

hope/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Contact, Portfolio

# Create your views here.
def index(request):
    portfolios = Portfolio.objects.all().order_by('-id')[:9]
    return render(request, 'hope/pages/index.html', {'portfolios': portfolios})
    
def about_view(request):
    portfolio = Portfolio.objects.all()
    return render(request, 'hope/pages/blog/about.html', {'portfolio':portfolio})    

def blog_view(request, slug):
    portfolio = Portfolio.objects.get(slug=slug)
    related = Portfolio.objects.exclude(slug=slug)[:4]
    return render(request, 'hope/pages/blog/blog.html', {'portfolio': portfolio, 'related': related})

def contact_view(request):
    if request.method == 'POST':
        name = request.POST['name']
        email = request.POST['email']
        subject = request.POST['subject']
        message = request.POST['message']

        contact = Contact(name=name, email=email, subject=subject, message=message)
        contact.save()

        return HttpResponse("OK")


def portfolio_view(request):
    portfolio = Portfolio.objects.all()
    return render(request, 'hope/pages/blog/allPortfolios.html', {'portfolio': portfolio})        


def about_me(request):
    return render(request, 'hope/pages/aboutMe.html')
    
def activities_view(request):
    return render(request, 'hope/pages/activitiesPage.html')
    
def donation_view(request):

    return render(request, 'hope/pages/donation.html')    

hope/templates/hope/pages/blog/about.html
{% extends "hope/pages/blog/blog-base.html" %} {% load static %} {% block content %}

<section class="pt-5" id="about">
    <div class="bg-light">
        <div class="container">
            <div class="row">
                <div class="col-md-8 text-justify">
                    <div class="col-md-12 pt-lg-5" id="abt">

                        <h2 class="mb-3">About Us</h2>
                        <p class="lead">
                            There is hope foundation group, is the society created on 1<sup>st</sup> of august 2020, consisting of both undergraduates, graduates, other supporters outside the campus, Created with the purpose of bringing back the living
                            hope to the thousands of people who are suffering outside over there, this includes, visiting orphanage centers, hospitals, drug addicted centers, and prisoners.
                        </p>
                        <p>
                            The group is open to any individual who will be touched to support this foundation in either way ,i.e providing money, clothes , Bibles , and other materials which will be helpfull while we will be conducting the Charity events;may God bless you as plan
                            to support His dearly Children;
                        </p>

                    </div>
                    <div class="col-md-12 pt-lg-5" id="mission">

                        <h2 class="mb-3">Our Mission</h2>
                        <p>The Greatest mission complies with the mission of Christ in luke 19;10 <q class="font-italic lead" style="background-color: aliceblue;"> For the son of man has come to seek and to save that which was lost</q> knowing this There
                            is Hope foundation group have joined hands together to support differrent people and beloved who are passing through hard times , this includes , orphans , prisoners, patients who are in the hospitals,and the Drug addicted
                            people.
                        </p>
                        <div class="image">
                            <img src="{% static 'assets/img/intro-carousel/1.jpg' %}" alt="" class="img-fluid h-100 p-3">
                        </div>
                        <p>The organisation will help them both physically, psychologically and spiritualy by providing them with their material needs, creating a friendship,socializing with them; But above all sharing with them the Words of life from the
                            HOLY BIBLE.</p>

                    </div>
                    <div class="col-md-12 pt-lg-5" id="plan">

                        <h2 class="mb-3">Our Plan</h2>
                        <p>There is hope foundation group has got different amazing plans to fullfill their dreams as follows;</p>
                        <ol>
                            <li>To have one charity event after every two months, where we will visit one of the groups in need,i.e orphans in their orphanage center and the line will follow up.</li>
                            <li>Every member who will be willing to join the team will contribute 5000/=Tsh ( 2 USD) as the subscription fee per month to sustain all plans and execution of the charity event Planed </li>
                            <div class="image pt-2">
                                <img src="{% static 'assets/img/intro-carousel/2.jpg' %}" alt="" class="img-fluid h-100 p-3">
                            </div>
                            <li>The organisation has created a project plan of producing Tshirt with the Brand <em>There is hope</em>, and all of the profit shall be directed to support the Foundation in all of its activities</li>
                        </ol>

                    </div>
                    <div class="col-md-12 pt-lg-5" id="vision">

                        <h2 class="mb-3">Our Vision</h2>
                        <p>Our vision is to restore and revive back the living Hope to the thousands of people who are passing through hard times in this life and those who are at the edge of giving up their lives, and showing them the Light of truth and
                            hope in this degenerate age.
                        </p>
                        <div class="image">
                            <img src="{% static 'assets/img/intro-carousel/5.jpg' %}" alt="" class="img-fluid h-100 p-3">
                        </div>
                        <strong>psalms 82;3-5</strong>
                        <blockquote class="col-md-11 offset-sm-1 font-italic" style="background-color: aliceblue;"> <i class="fa fa-quote-left"></i> Defend the poor and fatherless; do justice to the afflicted and needy; deliver the poor and the needy rid them out of the hand of the wicked; they know not; neither will they understand; they walk
                            on in darkness; all the foundations of the earth are out of course <i class="fa fa-quote-right"></i>. <abbr title="King James Version">KJV</abbr>
                        </blockquote>

                    </div>

                    <div class="about-author d-flex p-2 bg-light">
                        <div class="bio align-self-md-center mr-3" style="">
                            <img src="{% static 'assets/img/victor2.jpg' %}" alt="Image placeholder" class="mb-4" style="height: 150px; width: 150px; object-fit: cover; border-radius: 100%;">
                        </div>
                        <div class="desc align-self-md-center ">
                            <h3>Victor Jumanne Joshua</h3>
                            <p class="font-italic" style="word-wrap: break-word;">
                                <i class="fa fa-quote-left"></i> pure religion and undefiled before God and the Father is this, To visit the Fatherless and Widows in their affliction , and to keep oneself unspotted from the World james 1;27

                                <i class="fa fa-quote-right"></i>
                            </p>
                        </div>
                    </div>


                </div>
                <!-- .col-md-8 -->
                <div class="col-md-4 sidebar ftco-animate">

                    <div class="sidebar-box ftco-animate">
                        <div class="categories">
                            <h3>Categories <span>({{portfolio.count}})</span></h3>
                            <li><a href="{% url 'hope:portfolios' %}" data-filter=".filter-hospital">Hospital <span></span></a></li>
                            <li><a href="{% url 'hope:portfolios' %}">Prisons <span></span></a></li>
                            <li><a href="{% url 'hope:portfolios' %}">Orphanage <span></span></a></li>
                            <li><a href="{% url 'hope:portfolios' %}">Sobber house <span></span></a></li>
                            <!-- <li><a href="#">Foods <span>(14)</span></a></li>
                            <li><a href="#">Travel <span>(140)</span></a></li> -->
                        </div>
                    </div>


                    <!-- <div class="sidebar-box ftco-animate">
                        <h3>Tag Cloud</h3>
                        <div class="tagcloud">
                            <a href="#" class="tag-cloud-link">dish</a>
                            <a href="#" class="tag-cloud-link">menu</a>
                            <a href="#" class="tag-cloud-link">food</a>
                            <a href="#" class="tag-cloud-link">sweet</a>
                            <a href="#" class="tag-cloud-link">tasty</a>
                            <a href="#" class="tag-cloud-link">delicious</a>
                            <a href="#" class="tag-cloud-link">desserts</a>
                            <a href="#" class="tag-cloud-link">drinks</a>
                        </div>
                    </div> -->

                </div>

            </div>
        </div>
    </div>
</section>
<!-- .section -->


{% endblock content %}

hope/templates/hope/pages/blog/allPortfolios.html
{% extends "hope/pages/blog/blog-base.html" %} {% block content %}

<section id="portfolio" class="section-bg">
    <div class="container">

        <header class="section-header" id="title">
            <h3 class="section-title">Our Portfolio</h3>
        </header>

        <div class="row">
            <div class="col-lg-12">
                <ul id="portfolio-flters">
                    <li data-filter="*" class="filter-active">All</li>
                    <li data-filter=".filter-hospital">Hospital</li>
                    <li data-filter=".filter-prisons">Prisons</li>
                    <li data-filter=".filter-orphanage">Orphanage</li>
                    <li data-filter=".filter-drug_addiction">Drug Addiction</li>
                </ul>
            </div>
        </div>

        <div class="row portfolio-container">
            {% for portfolio in portfolio %} {% if portfolio.category == 'hospital' %}
            <div class="col-lg-4 col-md-6 portfolio-item filter-hospital wow fadeInUp">
                <div class="portfolio-wrap">
                    <figure>
                        <img src="{{ portfolio.img_url }}#{{portfolio.id}}" class="img-fluid" alt="">
                        <a href="{{ portfolio.img_url }}" data-lightbox="portfolio" data-title="{{ portfolio.title }}" class="link-preview" title="Preview"><i class="ion ion-eye"></i></a>
                        <a href="{% url 'hope:view' portfolio.slug %}#{{portfolio.id}}" class="link-details" title="More Details"><i class="ion ion-android-open"></i></a>
                    </figure>

                    <div class="portfolio-info">
                        <h4><a href="{% url 'hope:view' portfolio.slug %}#{{portfolio.id}}">{{ portfolio.title }}</a></h4>
                        <p>{{ portfolio.category }}</p>
                    </div>
                </div>
            </div>
            {% elif portfolio.category == 'prisons' %}
            <div class="col-lg-4 col-md-6 portfolio-item filter-prisons wow fadeInUp" data-wow-delay="0.1s">
                <div class="portfolio-wrap">
                    <figure>
                        <img src="{{ portfolio.img_url }}#{{portfolio.id}}" class="img-fluid" alt="">
                        <a href="{{ portfolio.img_url }}" class="link-preview" data-lightbox="portfolio" data-title="{{ portfolio.title }}" title="Preview"><i class="ion ion-eye"></i></a>
                        <a href="{% url 'hope:view' portfolio.slug %}#{{portfolio.id}}" class="link-details" title="More Details"><i class="ion ion-android-open"></i></a>
                    </figure>

                    <div class="portfolio-info">
                        <h4><a href="{% url 'hope:view' portfolio.slug %}#{{portfolio.id}}">{{ portfolio.title }}</a></h4>
                        <p>{{ portfolio.category }}</p>
                    </div>
                </div>
            </div>
            {% elif portfolio.category == 'orphanage' %}
            <div class="col-lg-4 col-md-6 portfolio-item filter-orphanage wow fadeInUp" data-wow-delay="0.1s">
                <div class="portfolio-wrap">
                    <figure>
                        <img src="{{ portfolio.img_url }}#{{portfolio.id}}" class="img-fluid" alt="">
                        <a href="{{ portfolio.img_url }}" class="link-preview" data-lightbox="portfolio" data-title="{{ portfolio.title }}" title="Preview"><i class="ion ion-eye"></i></a>
                        <a href="{% url 'hope:view' portfolio.slug %}#{{portfolio.id}}" class="link-details" title="More Details"><i class="ion ion-android-open"></i></a>
                    </figure>

                    <div class="portfolio-info">
                        <h4><a href="{% url 'hope:view' portfolio.slug %}#{{portfolio.id}}">{{ portfolio.title }}</a></h4>
                        <p>{{ portfolio.category }}</p>
                    </div>
                </div>
            </div>
            {% elif portfolio.category == 'drug_addiction' %}
            <div class="col-lg-4 col-md-6 portfolio-item filter-drug_addiction wow fadeInUp" data-wow-delay="0.1s">
                <div class="portfolio-wrap">
                    <figure>
                        <img src="{{ portfolio.img_url }}#{{portfolio.id}}" class="img-fluid" alt="">
                        <a href="{{ portfolio.img_url }}" class="link-preview" data-lightbox="portfolio" data-title="{{ portfolio.title }}" title="Preview"><i class="ion ion-eye"></i></a>
                        <a href="{% url 'hope:view' portfolio.slug %}#{{portfolio.id}}" class="link-details" title="More Details"><i class="ion ion-android-open"></i></a>
                    </figure>

                    <div class="portfolio-info">
                        <h4><a href="{% url 'hope:view' portfolio.slug %}#{{portfolio.id}}">{{ portfolio.title }}</a></h4>
                        <p>{{ portfolio.category }}</p>
                    </div>
                </div>
            </div>
            {% endif %} {% endfor %}

        </div>

    </div>
</section>
{% endblock content %}

hope/templates/hope/pages/blog/blog-base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>BizPage Bootstrap Template</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description"> {% load static %}
    <!-- Favicons -->
    <link href="{% static 'assets/img/favicon.png' %}" rel="icon">
    <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,700,700i|Montserrat:300,400,500,700" rel="stylesheet">

    <!-- Bootstrap CSS File -->
    <link href="{% static 'assets/lib/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Libraries CSS Files -->
    <link href="{% static 'assets/lib/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/lib/animate/animate.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/lib/ionicons/css/ionicons.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/lib/lightbox/css/lightbox.min.css' %}" rel="stylesheet">

    <!-- Main Stylesheet File -->
    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">
    <link href="{% static 'assets/css/styles.css' %}" rel="stylesheet">

    <!-- =======================================================
    Theme Name: BizPage
    Theme URL: https://bootstrapmade.com/bizpage-bootstrap-business-template/
    Author: BootstrapMade.com
    License: https://bootstrapmade.com/license/
  ======================================================= -->
</head>

<body>

    <!--==========================
    Header
  ============================-->
    <header id="header">
        <div class="container-fluid">

            <div id="logo" class="pull-left">
                <h1><a href="{% url 'hope:index' %}" class="scrollto">ThereIsHope</a></h1>
                <!-- Uncomment below if you prefer to use an image logo -->
                <!-- <a href="#intro"><img src="{% static 'assets/img/logo.png' %}" alt="" title="" /></a>-->
            </div>

            <!-- <nav id="nav-menu-container">
                <ul class="nav-menu">
                    <li class="menu-active"><a href="{% url 'hope:index' %}">Home</a></li>
                    <li><a href="#about">About Us</a></li>
                    <li><a href="#activities">Our Activities</a></li>
                    <li><a href="#portfolio">Portfolio</a></li>
                    <li><a href="#team">Team</a></li>
                    <li class="menu-has-children"><a href="">Drop Down</a>
                        <ul>
                            <li><a href="#">Drop Down 1</a></li>
                            <li><a href="#">Drop Down 3</a></li>
                            <li><a href="#">Drop Down 4</a></li>
                            <li><a href="#">Drop Down 5</a></li>
                        </ul>
                    </li>
                    <li><a href="#contact">Contact</a></li>
                </ul>
            </nav> -->
            <!-- #nav-menu-container -->
        </div>
    </header>
    <div class="hero-wrap" style="background-image: url('/static/assets/img/intro-carousel/bg_1.jpg');" data-stellar-background-ratio="0.5">
        <div class="overlay"></div>
        <div class="container">
            <div class="row no-gutters slider-text align-items-center justify-content-center" data-scrollax-parent="true">
                <div class="col-md-7 ftco-animate text-center" data-scrollax=" properties: { translateY: '70%' }">
                    <!-- <p class="breadcrumbs" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }"><span class="mr-2"><a href="index.html">Home</a></span> <span class="mr-2"><a href="blog.html">Blog</a></span> <span>Blog Details</span></p> -->
                    <h1 class="mb-3 bread" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }">Blog Details</h1>
                </div>
            </div>
        </div>
    </div>

    {% block content %} {% endblock content %} {% include "hope/footer/footer.html" %}


</html>

hope/templates/hope/pages/blog/blog.html
{% extends "hope/pages/blog/blog-base.html" %} {% block content %}
<!-- Page Content -->
<div class="container" id="{{portfolio.id}}">

    <!-- Portfolio Item Heading -->
    <h2 class="my-5">{{ portfolio.title }}
    </h2>

    <!-- Portfolio Item Row -->
    <div class="row">

        <div class="col-md-8" style="height: 400px;">
            <img class="img-fluid" src="{{ portfolio.img_url }}" alt="" style="width: 100%; object-fit: cover; height: 100%;">
        </div>

        <div class="col-md-4">
            <h3 class="my-3">Work Description</h3>
            <p>{{ portfolio.description }}
            </p>
            <h3 class="my-3">Project Details</h3>
            <ul>
                <li>Lorem Ipsum</li>
                <li>Dolor Sit Amet</li>
                <li>Consectetur</li>
                <li>Adipiscing Elit</li>
            </ul>
        </div>

    </div>
    <!-- /.row -->

    <!-- Related Projects Row -->
    <h3 class="my-4">Related Activities</h3>

    <div class="row">
        {% for related in related %}
        <div class="col-md-3 col-sm-6 mb-4 related">
            <a href="{% url 'hope:view' related.slug %}#{{ related.id }}">
                <img class="img-fluid" src="{{ related.img_url }}" alt="" style="object-fit: cover; height: 180px; width: 100%;">
            </a>
        </div>
        {% endfor %}

    </div>
    <!-- /.row -->

</div>
<!-- /.container -->
{% endblock content %}