ThereIsHope/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('hope.urls')),
    path('admins/', include('admins.urls')),
    path('admin/', admin.site.urls),
]

hope/urls.py
from django.contrib import admin
from django.urls import path
from . import views as v

app_name = 'hope'

urlpatterns = [
    path('', v.index, name='index'),
    path('about', v.about_view, name='about'),
    path('view/<slug:slug>', v.blog_view, name='view'),
    path('contactMessage', v.contact_view, name='message'),
    path('activities', v.activities_view, name='activities'),
    path('portfolios', v.portfolio_view, name='portfolios'),
    path('about-me', v.about_me, name='about_me'),
    path('donate', v.donation_view, name='donation'),
]

hope/models.py
from django.db import models
from django.utils.text import slugify

class Contact(models.Model):
    name        = models.CharField(max_length=255)
    email       = models.EmailField(max_length=254)
    subject     = models.CharField(max_length=50)
    message     = models.TextField()
    slug        = models.SlugField(max_length=140, unique=True, blank=True)
    date        = models.DateTimeField(blank=True, auto_now_add=True, null=True)

    def __str__(self):
        return self.subject

    def get_unique_slug(self):
        slug = slugify(self.subject)  
        unique_slug = slug

        num = 1
        while Contact.objects.filter(slug=unique_slug).exists():
            unique_slug = '{}-{}'.format(slug, num)

            num += 1

        return unique_slug


    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = self.get_unique_slug()
        super().save(*args, **kwargs)


class Portfolio(models.Model):
    HOSP    =  'hospital'
    ORPH   =  'orphanage'
    PRIS     =  'prisons'
    DRU =  'drug_addiction'

    CATEGORY_SELECT = [
        (HOSP, 'Hospital'),
        (ORPH, 'Orphanage'),
        (PRIS, 'Prisons'),
        (DRU, 'Drug addiction center')
    ]
    

    title           =   models.CharField(max_length=225)
    description     =   models.TextField()
    category        =   models.CharField(choices=CATEGORY_SELECT, max_length=20)
    date            =   models.DateField(auto_now_add=True)
    img_url         =   models.URLField(max_length=2000)
    slug            =   models.SlugField(max_length=140, unique=True, blank=True)


    def __str__(self):
        return self.title
    
    def get_unique_slug(self):
        slug    =   slugify(self.title)
        unigue_slug =   slug

        num = 1
        while Portfolio.objects.filter(slug=unigue_slug).exists():
            unigue_slug = '{}_{}'.format(slug, num)

            num += 1

        return unigue_slug


    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = self.get_unique_slug()
        super().save(*args, **kwargs)       

        

hope/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Contact, Portfolio

# Create your views here.
def index(request):
    portfolios = Portfolio.objects.all().order_by('-id')[:9]
    return render(request, 'hope/pages/index.html', {'portfolios': portfolios})
    
def about_view(request):
    portfolio = Portfolio.objects.all()
    return render(request, 'hope/pages/blog/about.html', {'portfolio':portfolio})    

def blog_view(request, slug):
    portfolio = Portfolio.objects.get(slug=slug)
    related = Portfolio.objects.exclude(slug=slug)[:4]
    return render(request, 'hope/pages/blog/blog.html', {'portfolio': portfolio, 'related': related})

def contact_view(request):
    if request.method == 'POST':
        name = request.POST['name']
        email = request.POST['email']
        subject = request.POST['subject']
        message = request.POST['message']

        contact = Contact(name=name, email=email, subject=subject, message=message)
        contact.save()

        return HttpResponse("OK")


def portfolio_view(request):
    portfolio = Portfolio.objects.all()
    return render(request, 'hope/pages/blog/allPortfolios.html', {'portfolio': portfolio})        


def about_me(request):
    return render(request, 'hope/pages/aboutMe.html')
    
def activities_view(request):
    return render(request, 'hope/pages/activitiesPage.html')
    
def donation_view(request):

    return render(request, 'hope/pages/donation.html')    

hope/templates/hope/pages/activitiesPage.html
{% extends "hope/pages/blog/blog-base.html" %} {% load static %} {% block content %}
<section class="pt-5" id="activities">
    <div class="bg-light">
        <div class="container">
            <div class="row">
                <div class="col-md-8 text-justify">
                    <div class="col-md-12 pt-lg-5" id="first">

                        <h2 class="mb-3">Our Activities</h2>
                        <div id="1">
                            <h4>1. VISITING THE ORPHAGE CENTERS</h4>
                            <p>The intention of visiting these centers is to relieve sufferings and necessities of orphans by supplying their needs but also to socialize with them in order to provide psychological support. Providing a session of encouragement
                                from the Word of God, accompanied with prayers will help in restoring back the hope to their lives</p>
                        </div>

                        <div id="2">
                            <h4>2. COMFORTING PATIENTS FROM DIFFERENT HOSPITALS</h4>
                            <p>Nevertheless, that we are providing physical needs to those who are sick, but a tender visit and comfort in their chronic illness accompanied with promises from the Word of God and sweet words of prayers and love, will avail
                                much and cause the cords of hope that were broken to vibrate once more and rays of the living hope will keep on shining in their Hearts.</p>
                        </div>

                        <div id="3">
                            <h4>3. TO VISIT PRISONERS</h4>
                            <p>Another step that is crucial is to comfort the prisoners, helping them with their basic needs, distributing to them books that will help them to find the real purpose of life and revive back their living hope.</p>
                        </div>

                        <div id="4">
                            <h4>4. SUPPORTING ELDERLY PEOPLE </h4>
                            <p>Many elderly individuals suffer from loneliness, neglect and psychological distress due to their dependence, as the team we have to take serious measures in supporting and influencing the lives of elderly people, both physical,
                                psychological and spiritual support are needed by this special group, with all ability on our hands we are striving to bring the smile upon the faces of this beloveds. </p>
                        </div>

                        <div id="5">
                            <h4>5. VISITING SCHOOLS AND IMPACTING YOUTHS LIFE</h4>
                            <p>Through motivations, and providing good presentations that will enlights the mind of many youth will bring a great impact upon many students. It will be the seed that will germinate and produce many fruits. Dr Ben Carson once
                                said
                                <i class="fa fa-quote-left"></i>
                                <span class="lead"> Having been born on the wrong side of track does not mean that the birth place has to remain the permanent address, it’s not where we are coming from but where we are going that counts.</span>
                                <i class="fa fa-quote-right"></i>
                            </p>
                        </div>

                        <div id="6">
                            <h4>6. CONDUCTING HEALTH SEMINORS</h4>
                            <p>Prevention is better than cure. We will join hands together with other members of health professions to create an education platform on health issues, including nutrition education, preparation of the food, benefits of exercise,
                                knowledge of several diseases and their natural remedies, many are crying with such diseases which could have been easily prevented but due to lack of sufficient knowledge they found themselves prey for this chronic disease.</p>
                        </div>
                    </div>


                </div>
                <!-- .col-md-8 -->
                <div class="col-md-4 sidebar ftco-animate">

                    <div class="sidebar-box ftco-animate">
                        <div class="categories">
                            <h3>Categories <span>({{portfolio.count}})</span></h3>
                            <li><a href="{% url 'hope:portfolios' %}" data-filter=".filter-hospital">Hospital <span></span></a></li>
                            <li><a href="{% url 'hope:portfolios' %}">Prisons <span></span></a></li>
                            <li><a href="{% url 'hope:portfolios' %}">Orphanage <span></span></a></li>
                            <li><a href="{% url 'hope:portfolios' %}">Sobber house <span></span></a></li>
                            <!-- <li><a href="#">Foods <span>(14)</span></a></li>
                            <li><a href="#">Travel <span>(140)</span></a></li> -->
                        </div>
                    </div>


                    <!-- <div class="sidebar-box ftco-animate">
                        <h3>Tag Cloud</h3>
                        <div class="tagcloud">
                            <a href="#" class="tag-cloud-link">dish</a>
                            <a href="#" class="tag-cloud-link">menu</a>
                            <a href="#" class="tag-cloud-link">food</a>
                            <a href="#" class="tag-cloud-link">sweet</a>
                            <a href="#" class="tag-cloud-link">tasty</a>
                            <a href="#" class="tag-cloud-link">delicious</a>
                            <a href="#" class="tag-cloud-link">desserts</a>
                            <a href="#" class="tag-cloud-link">drinks</a>
                        </div>
                    </div> -->

                </div>

            </div>
        </div>
    </div>
</section>
<!-- .section -->

<style>
    /* Extra small devices (phones, 600px and down) */
    
    @media only screen and (max-width: 600px) {
        h4 {
            text-align: center;
        }
    }
    /* Small devices (portrait tablets and large phones, 600px and up) */
    
    @media only screen and (min-width: 600px) {
        h4 {
            text-align: left;
        }
    }
</style>


{% endblock content %}

hope/templates/hope/pages/donation.html
<!DOCTYPE html>

<head>
    <!-- Add meta tags for mobile and IE -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
</head>

<body>
    <!-- Set up a container element for the button -->
    <div id="paypal-button-container"></div>

    <!-- Include the PayPal JavaScript SDK -->
    <script src="https://www.paypal.com/sdk/js?client-id=sb&currency=USD"></script>

    <script>
        // Render the PayPal button into #paypal-button-container
        paypal.Buttons({

            // Set up the transaction
            createOrder: function(data, actions) {
                return actions.order.create({
                    purchase_units: [{
                        amount: {
                            value: '0.01'
                        }
                    }]
                });
            },

            // Finalize the transaction
            onApprove: function(data, actions) {
                return actions.order.capture().then(function(details) {
                    // Show a success message to the buyer
                    alert('Transaction completed by ' + details.payer.name.given_name + '!');
                });
            }


        }).render('#paypal-button-container');
    </script>
</body>

hope/templates/hope/pages/index.html
{% extends 'hope/main/main.html' %} {% load static %} {% block content %}

<!--==========================
      About Us Section
    ============================-->
<section id="about">
    <div class="container">

        <header class="section-header">
            <h3>About Us</h3>
            <p>
                There is hope foundation group, is the society created on 1<sup>st</sup> of august 2020, consisting of both undergraduates, graduates, other supporters outside the campus, Created with the purpose of bringing back the living hope to the
                thousands of people who are suffering outside over there, <a href="{% url 'hope:about' %}#abt">Read more..</a>
            </p>
        </header>

        <div class="row about-cols">

            <div class="col-md-4 wow fadeInUp">
                <div class="about-col">
                    <div class="img">
                        <a href="{% url 'hope:about' %}#mission" class="h-100">
                            <img src="{% static 'assets/img/mission.jpg' %}" alt="" class="w-100 h-100">
                            <div class="icon"><i class="ion-ios-speedometer-outline"></i></div>
                        </a>
                    </div>
                    <h2 class="title"><a href="{% url 'hope:about' %}#mission">Our Mission</a></h2>
                    <p>
                        To help them both physically, psychologically and spiritualy by providing them with their material needs, creating a friendship,socializing with them; But above all sharing with them the Words of life from the HOLY BIBLE.
                    </p>
                </div>
            </div>

            <div class="col-md-4 wow fadeInUp" data-wow-delay="0.1s">
                <div class="about-col">
                    <div class="img">
                        <a href="{% url 'hope:about' %}#plan" class="h-100">
                            <img src="{% static 'assets/img/plan.jpeg' %}" alt="" class="w-100 h-100">
                            <div class="icon"><i class="ion-ios-list-outline"></i></div>
                        </a>
                    </div>
                    <h2 class="title"><a href="{% url 'hope:about' %}#plan">Our Plan</a></h2>
                    <p>
                        To have one charity event after every two months, where we will visit one of the groups in need,i.e orphans in their orphanage center and the line will follow up, producing Tshirt with the Brand <em>There is hope</em>,..
                    </p>
                </div>
            </div>

            <div class="col-md-4 wow fadeInUp" data-wow-delay="0.2s">
                <div class="about-col">
                    <div class="img">
                        <a href="{% url 'hope:about' %}#vision" class="h-100">
                            <img src="{% static 'assets/img/vision.jpg' %}" alt="" class="w-100 h-100">
                            <div class="icon"><i class="ion-ios-eye-outline"></i></div>
                        </a>
                    </div>
                    <h2 class="title"><a href="{% url 'hope:about' %}#vision">Our Vision</a></h2>
                    <p>
                        Our vision is to restore and revive back the living Hope to the thousands of people who are passing through hard times in this life and those who are at the edge of giving up their lives, and showing them the Light of truth...
                    </p>
                </div>
            </div>

        </div>

    </div>
</section>
<!-- #about -->

<!--==========================
  Activities Section
============================-->
{% include "hope/pages/indexComponents/activities.html" %}
<!-- #Activities -->

<!--==========================
  Call To Action Section
============================-->
<section id="call-to-action" class="wow fadeIn">
    <div class="row">
        <div class="col-md-6">
            <div class="container text-center">
                <h3>What is ThereIsHope?</h3>
                <p> There is hope foundation group, is the society created on 1st of august 2020, consisting of both undergraduates, graduates, other supporters outside the campus, Created with the purpose of bringing back the living hope to the thousands
                    of people who are suffering outside over there</p>
                <a class="cta-btn" href="{% url 'hope:about' %}#abt">See More</a>
            </div>
        </div>
        <div class="col-md-6">
            <div class="col-md-10">
                <iframe width="100%" height="315" src="https://www.youtube.com/embed/Jo8lqCyoqHs" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
            </div>
        </div>
    </div>
</section>
<!-- #call-to-action -->



<!--==========================
  Portfolio Section
============================-->
{% include "hope/pages/indexComponents/potfolio.html" %}
<!-- #portfolio -->



<!--==========================
  Clients Section
============================-->
<!-- <section id="testimonials" class="section-bg wow fadeInUp">
    <div class="container">

        <header class="section-header">
            <h3>Testimonials</h3>
        </header>

        <div class="owl-carousel testimonials-carousel">

            <div class="testimonial-item">
                <img src="{% static 'assets/img/testimonial-1.jpg' %}" class="testimonial-img" alt="">
                <h3>Saul Goodman</h3>
                <h4>Ceo &amp; Founder</h4>
                <p>
                    <img src="{% static 'assets/img/quote-sign-left.png' %}" class="quote-sign-left" alt=""> Proin iaculis purus consequat sem cure digni ssim donec porttitora entum suscipit rhoncus. Accusantium quam, ultricies eget id, aliquam eget nibh
                    et. Maecen aliquam, risus at semper.
                    <img src="{% static 'assets/img/quote-sign-right.png' %}" class="quote-sign-right" alt="">
                </p>
            </div>

            <div class="testimonial-item">
                <img src="{% static 'assets/img/testimonial-2.jpg' %}" class="testimonial-img" alt="">
                <h3>Sara Wilsson</h3>
                <h4>Designer</h4>
                <p>
                    <img src="{% static 'assets/img/quote-sign-left.png' %}" class="quote-sign-left" alt=""> Export tempor illum tamen malis malis eram quae irure esse labore quem cillum quid cillum eram malis quorum velit fore eram velit sunt aliqua
                    noster fugiat irure amet legam anim culpa.
                    <img src="{% static 'assets/img/quote-sign-right.png' %}" class="quote-sign-right" alt="">
                </p>
            </div>

            <div class="testimonial-item">
                <img src="{% static 'assets/img/testimonial-3.jpg' %}" class="testimonial-img" alt="">
                <h3>Jena Karlis</h3>
                <h4>Store Owner</h4>
                <p>
                    <img src="{% static 'assets/img/quote-sign-left.png' %}" class="quote-sign-left" alt=""> Enim nisi quem export duis labore cillum quae magna enim sint quorum nulla quem veniam duis minim tempor labore quem eram duis noster aute amet
                    eram fore quis sint minim.
                    <img src="{% static 'assets/img/quote-sign-right.png' %}" class="quote-sign-right" alt="">
                </p>
            </div>

            <div class="testimonial-item">
                <img src="{% static 'assets/img/testimonial-4.jpg' %}" class="testimonial-img" alt="">
                <h3>Matt Brandon</h3>
                <h4>Freelancer</h4>
                <p>
                    <img src="{% static 'assets/img/quote-sign-left.png' %}" class="quote-sign-left" alt=""> Fugiat enim eram quae cillum dolore dolor amet nulla culpa multos export minim fugiat minim velit minim dolor enim duis veniam ipsum anim magna
                    sunt elit fore quem dolore labore illum veniam.
                    <img src="{% static 'assets/img/quote-sign-right.png' %}" class="quote-sign-right" alt="">
                </p>
            </div>

            <div class="testimonial-item">
                <img src="{% static 'assets/img/testimonial-5.jpg' %}" class="testimonial-img" alt="">
                <h3>John Larson</h3>
                <h4>Entrepreneur</h4>
                <p>
                    <img src="{% static 'assets/img/quote-sign-left.png' %}" class="quote-sign-left" alt=""> Quis quorum aliqua sint quem legam fore sunt eram irure aliqua veniam tempor noster veniam enim culpa labore duis sunt culpa nulla illum cillum
                    fugiat legam esse veniam culpa fore nisi cillum quid.
                    <img src="{% static 'assets/img/quote-sign-right.png' %}" class="quote-sign-right" alt="">
                </p>
            </div>

        </div>

    </div>
</section> -->
<!-- #testimonials -->

<!--==========================
  Team Section
============================-->
<section id="team" class="wow fadeInUp">
    <div class="container">
        <div class="section-header wow fadeInUp">
            <h3>Team</h3>
            <p>ThereIsHope top management team</p>
        </div>

        <div class="owl-carousel testimonials-carousel">
            <div class="row">
                <div class="col-lg-3 col-md-6 wow fadeInUp tm">
                    <div class="member h-100">
                        <img src="{% static 'assets/img/victor2.jpg' %}" class="w-100 h-100" alt="">
                        <div class="member-info">
                            <div class="member-info-content">
                                <h4>Victor Jumanne Joshua </h4>
                                <span>Chair Person</span>
                                <!-- <div class="social">
                                    <a href=""><i class="fa fa-twitter"></i></a>
                                    <a href=""><i class="fa fa-facebook"></i></a>
                                    <a href=""><i class="fa fa-google-plus"></i></a>
                                    <a href=""><i class="fa fa-linkedin"></i></a>
                                </div> -->
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-lg-3 col-md-6 wow fadeInUp tm" data-wow-delay="0.1s">
                    <div class="member">
                        <img src="{% static 'assets/img/venture.jpg' %}" class="w-100 h-100" alt="">
                        <div class="member-info">
                            <div class="member-info-content">
                                <h4>Liberatus Boniventure </h4>
                                <span>Deputy Chairperson</span>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-lg-3 col-md-6 wow fadeInUp tm" data-wow-delay="0.2s">
                    <div class="member">
                        <img src="{% static 'assets/img/paul.jpg' %}" class="w-100 h-100" alt="">
                        <div class="member-info">
                            <div class="member-info-content">
                                <h4>Nyang'oro Paul Mahamba </h4>
                                <span>Secretary</span>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-lg-3 col-md-6 wow fadeInUp tm" data-wow-delay="0.3s">
                    <div class="member">
                        <img src="{% static 'assets/img/frida.jpg' %}" class="w-100 h-100" alt="">
                        <div class="member-info">
                            <div class="member-info-content">
                                <h4>Geofrida Joseph Oisso</h4>
                                <span>Deputy Secretary</span>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
            <div class="row">
                <div class="col-lg-3 col-md-6 wow fadeInUp tm" data-wow-delay="0.3s">
                    <div class="member">
                        <img src="{% static 'assets/img/otieno.jpg' %}" class="w-100 h-100" alt="">
                        <div class="member-info">
                            <div class="member-info-content">
                                <h4>Geoffrey Otieno</h4>
                                <span>Treasurer</span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 wow fadeInUp tm" data-wow-delay="0.3s">
                    <div class="member">
                        <img src="{% static 'assets/img/listen.jpg' %}" class="w-100 h-100" alt="">
                        <div class="member-info">
                            <div class="member-info-content">
                                <h4>Godlisten Suruwale</h4>
                                <span>Communication Director</span>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </div>
</section>
<!-- #team -->

<!--==========================
  Contact Section
============================-->
{% include "hope/pages/indexComponents/contact.html" %}
<!-- #contact -->

<style>
    .tm {
        height: 300px;
        margin-top: 5px;
    }
    
    .member {
        height: 100%;
    }
    
    .member img {
        object-fit: cover;
    }
    
    .img {
        height: 200px;
    }
    
    .img a img {
        object-fit: cover;
    }
</style>

{% endblock content %}