ThereIsHope/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('hope.urls')),
    path('admins/', include('admins.urls')),
    path('admin/', admin.site.urls),
]

admins/urls.py
from django.contrib import admin
from django.urls import path
from . import views as v

app_name = 'admins'

urlpatterns = [
    path('login', v.login, name='login'),
    path('logout', v.logout_view, name='logout'),
    path('dashboard', v.home_dashboard, name='dashboard'),
    path('user_profile/<int:id>', v.user_profile, name='user_profile'),
    path('update_profile/<int:id>', v.update_profile, name='update_profile'),
    path('users', v.users_view, name='users'),
    path('inbox', v.inbox_view, name='inbox'),
    path('inbox/<slug:slug>', v.email_view, name='read_email'),
    path('update-staff/<int:id>', v.update_staff, name='updateStaff'),
    path('portfolio', v.portfolio_view, name='portfolio'),
    path('portfolio-update/<slug:slug>', v.update_portfolio, name='updatePortfolio'),
    path('createPortfolio', v.create_portfolio, name='createPortfolio'),
    path('deletePortfolio/<slug:slug>', v.delete_portfolio, name='deletePortfolio'),

    # updating password
    path('user_profile/updatePassword/<int:id>', v.update_password, name='updatePassword'),

    # events
    path('events', v.events_view, name='events')
]

hope/urls.py
from django.contrib import admin
from django.urls import path
from . import views as v

app_name = 'hope'

urlpatterns = [
    path('', v.index, name='index'),
    path('about', v.about_view, name='about'),
    path('view/<slug:slug>', v.blog_view, name='view'),
    path('contactMessage', v.contact_view, name='message'),
    path('activities', v.activities_view, name='activities'),
    path('portfolios', v.portfolio_view, name='portfolios'),
    path('about-me', v.about_me, name='about_me'),
    path('donate', v.donation_view, name='donation'),
]

admins/templates/admins/components/events.html
{% extends "admins/basic.html" %} {% block content %}
<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="header">
                <h2>
                    <strong>Tabs</strong> With Animations</h2>
                <ul class="header-dropdown m-r--5">
                    <li class="dropdown">
                        <a href="#" onClick="return false;" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                            <i class="material-icons">more_vert</i>
                        </a>
                        <ul class="dropdown-menu pull-right">
                            <li>
                                <a href="#" onClick="return false;">Action</a>
                            </li>
                            <li>
                                <a href="#" onClick="return false;">Another action</a>
                            </li>
                            <li>
                                <a href="#" onClick="return false;">Something else here</a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
            <div class="body">
                <div class="row clearfix">
                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                        <!-- Nav tabs -->
                        <ul class="nav nav-tabs tab-nav-right" role="tablist">
                            <li role="presentation">
                                <a href="#home_animation_2" data-toggle="tab" class="active show">Coming Events</a>
                            </li>
                            <li role="presentation">
                                <a href="#profile_animation_2" data-toggle="tab">Completed Events</a>
                            </li>
                            <li role="presentation">
                                <a href="#messages_animation_2" data-toggle="tab">Postponed Events</a>
                            </li>
                        </ul>
                        <!-- Tab panes -->
                        <div class="tab-content">
                            <div role="tabpanel" class="tab-pane animated fadeInRight active show" id="home_animation_2">
                                {% include "../components/eventsComponents/pending_events.html" %}
                            </div>
                            <div role="tabpanel" class="tab-pane animated fadeInRight" id="profile_animation_2">
                                {% include "../components/eventsComponents/completed_events.html" %}
                            </div>
                            <div role="tabpanel" class="tab-pane animated fadeInRight" id="messages_animation_2">
                                {% include "../components/eventsComponents/postponed_events.html" %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
                <div class="modal fade" id="mo{{event.id}}" tabindex="-1" role="dialog" aria-labelledby="formModal" aria-hidden="true" style="display: none;">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="formModal">Update event</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">×</span>
                                </button>
                            </div>
                            <form action="" method="POST">
                                {% csrf_token %}
                                <div class="modal-body">
                                    <div class="row">
                                        <div class="col-md-6">
                                            <label>Title</label>
                                            <div class="form-group">
                                                <div class="form-line">
                                                    <input type="text" name="title" class="form-control" value="{{event.title}}">
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <label>category</label>
                                            <div class="form-group">
                                                <div class="form-line">
                                                    <select type="text" name="category" class="form-control">
                                                        <option  value="{{event.category}}"> {{event.category}}</option>
                                                        <option value='hospital'>hospital</option>
                                                        <option value="prisons">prisons</option>
                                                        <option value="drug_addiction">drug addicts</option>
                                                        <option value="orphanage">orphanage</option>
                                                    </select>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-12">
                                        <label>Description</label>
                                        <div class="form-group">
                                            <div class="form-line">
                                                <textarea rows="3" type="text" name="description" class="form-control" z>{{event.description}}</textarea>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-12">
                                            <label>image_url</label>
                                            <div class="form-group">
                                                <div class="form-line">
                                                    <input type="text" name="img_url" class="form-control" value={{event.img_url}}>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <br>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-danger waves-effect" data-dismiss="modal">Cancel</button>
                                    <button type="submit" class="btn btn-info waves-effect">Update</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>{% endblock content %}

admins/templates/admins/components/inbox.html
{% extends "admins/basic.html" %} {% block content %}

<div class="block-header">
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <ul class="breadcrumb breadcrumb-style ">
                <li class="breadcrumb-item">
                    <h4 class="page-title">Inbox</h4>
                </li>
                <li class="breadcrumb-item bcrumb-1">
                    <a href="../../index.html">
                        <i class="fas fa-home"></i> Home</a>
                </li>
                <li class="breadcrumb-item bcrumb-2">
                    <a href="#" onClick="return false;">Email</a>
                </li>
                <li class="breadcrumb-item active">Inbox</li>
            </ul>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-3 col-lg-3">
        <div class="card">
            <div class="body">
                <div id="mail-nav">
                    <button type="button" class="btn btn-success waves-effect m-b-15">COMPOSE</button>
                    <ul class="" id="mail-folders">
                        <li class="active">
                            <a href="mail-inbox.html" title="Inbox">Inbox
                                        <span class="pull-right badge bg-orange">{{count}}</span>
                                    </a>
                        </li>

                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-9 col-lg-9">
        <div class="card">
            <div class="boxs mail_listing">
                <div class="inbox-center table-responsive">
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th class="text-center">
                                    <label class="form-check-label">
                                                <input type="checkbox">
                                                <span class="form-check-sign"></span>
                                            </label>
                                </th>
                                <th colspan="3">
                                    <div class="inbox-header">
                                        <div class="mail-option no-pad-left">
                                            <div class="email-btn-group m-l-15">
                                                <a href="#" class="col-dark-gray waves-effect m-r-20" title="back">
                                                    <i class="material-icons">keyboard_return</i>
                                                </a>
                                                <a href="#" class="col-dark-gray waves-effect m-r-20" title="Archive">
                                                    <i class="material-icons">archive</i>
                                                </a>
                                                <a href="#" class="col-dark-gray waves-effect m-r-20" title="Error">
                                                    <i class="material-icons">error</i>
                                                </a>
                                                <a href="#" class="col-dark-gray waves-effect m-r-20" title="Delete">
                                                    <i class="material-icons">delete</i>
                                                </a>
                                                <a href="#" class="col-dark-gray waves-effect m-r-20" title="Folders">
                                                    <i class="material-icons">folder</i>
                                                </a>
                                                <a href="#" class="col-dark-gray waves-effect m-r-20" title="Tag">
                                                    <i class="material-icons">local_offer</i>
                                                </a>
                                                <a class="dropdown-toggle waves-effect waves-effect col-dark-gray" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">More</a>
                                                <ul class="dropdown-menu pull-right">
                                                    <li>
                                                        <a href="#" onClick="return false;" class=" waves-effect waves-block">Mark
                                                                    as Read</a>
                                                    </li>
                                                    <li>
                                                        <a href="#" onClick="return false;" class=" waves-effect waves-block">Spam</a>
                                                    </li>
                                                    <li>
                                                        <a href="#" onClick="return false;" class=" waves-effect waves-block">Delete</a>
                                                    </li>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                </th>
                                <th class="hidden-xs" colspan="2">
                                    <div class="pull-right">
                                        <div class="email-btn-group m-l-15">
                                            <a href="#" class="col-dark-gray waves-effect m-r-20" title="back">
                                                <i class="material-icons">navigate_before</i>
                                            </a>
                                            <a href="#" class="col-dark-gray waves-effect m-r-20" title="Archive">
                                                <i class="material-icons">navigate_next</i>
                                            </a>
                                        </div>
                                    </div>
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for contact in contacts %}
                            <tr class="unread">
                                <td class="tbl-checkbox">
                                    <label class="form-check-label">
                                                <input type="checkbox">
                                                <span class="form-check-sign"></span>
                                            </label>
                                </td>
                                <td class="hidden-xs">
                                    <i class="material-icons">star_border</i>
                                </td>
                                <td class="hidden-xs">{{contact.name}}</td>
                                <td class="max-texts">
                                    <a href="{% url 'admins:read_email' contact.slug %}">
                                        <span class="label l-bg-purple shadow-style m-r-10">{{contact.subject | truncatechars:5}}..</span> {{ contact.message | truncatechars:60 }}...</a>
                                </td>
                                <td class="text-laft"> {{contact.date}} </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="row">
                    <div class="col-sm-7 ">
                        <p class="p-15">Showing 1 - 15 of 200</p>
                    </div>
                    <div class="col-sm-5 text-right">
                        <div class="pull-right p-15">
                            <button type="button" class="btn btn-primary">
                                        <i class="material-icons">navigate_before</i>
                                    </button>
                            <button type="button" class="btn btn-primary">
                                        <i class="material-icons">navigate_next</i>
                                    </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

admins/templates/admins/components/profile.html
{% extends "admins/basic.html" %} {% block content %}
<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <!-- <div class="card">
            <div class="header">
                <h2>
                    <strong>Vertical</strong> Layout With Floating Label</h2>
                <ul class="header-dropdown m-r--5">
                    <li class="dropdown">
                        <a href="#" onclick="return false;" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                            <i class="material-icons">more_vert</i>
                        </a>
                        <ul class="dropdown-menu pull-right">
                            <li>
                                <a href="#" onclick="return false;">Action</a>
                            </li>
                            <li>
                                <a href="#" onclick="return false;">Another action</a>
                            </li>
                            <li>
                                <a href="#" onclick="return false;">Something else here</a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
            <div class="body">
                <form action="{% url 'admins:update_profile' profile.id %}" method="POST">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group form-float">
                                <div class="form-line">
                                    <input type="text" id="fname" name="fname" class="form-control" value="{{profile.first_name}}">
                                    <label class="form-label">First Name</label>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group form-float">
                                <div class="form-line">
                                    <input type="text" id="lname" name="lname" class="form-control" value="{{profile.last_name}}">
                                    <label class="form-label">Last Name</label>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group form-float">
                        <div class="form-line">
                            <input type="text" id="email_address" name="email" class="form-control" value="{{profile.email}}">
                            <label class="form-label">Email Address</label>
                        </div>
                    </div>
                    <div class="form-group form-float">
                        <div class="form-line">
                            <input type="text" id="username" name="username" class="form-control" value="{{profile.username}}">
                            <label class="form-label">Username</label>
                        </div>
                    </div>
                    <div class="form-group form-float">
                        <div class="">
                            <label class="form-label bg-blue col-sm-2 btn-border-radius text-center p-1" id="pass" style="cursor: pointer;">Update Password</label>
                        </div>
                    </div>
                    <div class="form-group form-float" style="display: none;" id="passField">
                        <div class="form-line">
                            <input type="password" id="password1" class="form-control">
                            <label class="form-label">Password</label>
                        </div>
                    </div>
                    <br>
                    <button type="submit" class="btn btn-primary m-t-15 waves-effect">update</button>
                </form>
            </div>
        </div> -->
    </div>
</div>

<div>
    <div class="row">
        <div class="col-md-4">
            <h5>Profile Information</h5>
            <p>Update your account's profile information and email address.</p>
        </div>
        <div class="col-md-8">
            <div class="card shadow">
                <div class="card-body">
                    <form action="{% url 'admins:update_profile' profile.id %}" method="POST">
                        {% csrf_token %}
                        <div class="col-md-10">
                            <div class="form-group">
                                <label for="fname">First Name</label>
                                <input type="text" name="first_name" class="form-control" id="fname" value="{{profile.first_name}}">
                            </div>
                            <div class="form-group">
                                <label for="lname">Last Name</label>
                                <input type="text" name="last_name" class="form-control" id="lname" value="{{profile.last_name}}">
                            </div>
                            <div class="form-group">
                                <label for="exampleInputEmail1">Email address</label>
                                <input type="email" name="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" value="{{profile.email}}">
                                <!-- <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small> -->
                            </div>
                            <div class="row">
                                <div class="form-group col-md-6">
                                    <label for="username">Username</label>
                                    <div>
                                        <input type="text" name="username" class="form-control" id="username" value="{{profile.username}}">
                                    </div>
                                </div>
                                <div class="form-group col-md-6">
                                    <label for="gender">Gender</label>
                                    <select type="text" name="gender" class="form-control" id="gender">
                                        <option value="{{profile.profile.gender}}">{{profile.profile.gender}}</option>
                                        <option value="M">Male</option>
                                        <option value="F">Female</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                        <button type="submit" class="btn btn-secondary float-right">save</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <hr />

    <div class="row">
        <div class="col-md-4">
            <h5>Update Password</h5>
            <p>Ensure your account is using a long, random password to stay secure.</p>
        </div>
        <div class="col-md-8">
            <div class="alert alert-success alert-dismissible fade show success" role="alert" style="display: none;">
                <p id="msg"></p>
                <button type="button" class="close" id="closeSuccess" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="alert alert-warning alert-dismissible fade show error" role="alert" style="display: none;">
                <p id="info"></p>
                <button type="button" class="close" id="closeError" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="card shadow-lg">
                <div class="card-body">
                    <form id="password-form">
                        <div class="col-md-10">
                            <div class="form-group">
                                <label for="passwordCurr">Current password</label>
                                <input type="password" name="currentPass" class="form-control" id="passwordCurr" required>
                                <span id="currPass" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label for="passwordNew">New Password</label>
                                <input type="password" name="password" class="form-control" id="passwordNew" required>
                                <span id="passerror" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label for="passwordConf">New Password</label>
                                <input type="password" name="passwordConf" class="form-control" id="passwordConf" required>
                                <span id="conferror" class="text-danger"></span>
                            </div>
                        </div>
                        <button id="changePassword" class="btn btn-secondary float-right">Save</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

admins/templates/admins/components/read_email.html
{% extends "admins/basic.html" %} {% block content %}

<div class="block-header">
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <ul class="breadcrumb breadcrumb-style ">
                <li class="breadcrumb-item">
                    <h4 class="page-title">View Mail</h4>
                </li>
                <li class="breadcrumb-item bcrumb-1">
                    <a href="../../index.html">
                        <i class="fas fa-home"></i> Home</a>
                </li>
                <li class="breadcrumb-item bcrumb-2">
                    <a href="#" onClick="return false;">Email</a>
                </li>
                <li class="breadcrumb-item active">View Mail</li>
            </ul>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-9 col-lg-9">
        <div class="card">
            <div class="boxs mail_listing">
                <div class="inbox-body no-pad">
                    <section class="mail-list">
                        <div class="mail-sender">
                            <div class="mail-heading">
                                <h4 class="vew-mail-header">
                                    <b>{{info.subject}}</b>
                                </h4>
                            </div>
                            <hr>
                            <div class="media">
                                <a href="#" class="table-img m-r-15">
                                    <img alt="" src="../../assets/images/user/user2.jpg">
                                </a>
                                <div class="media-body">
                                    <span class="date pull-right">{{info.date}}</span>
                                    <h4 class="text-primary">{{info.name}}</h4>
                                    <small class="text-muted">From: <a href="mailto:{{info.email}}">{{info.email}}</a></small>
                                </div>
                            </div>
                        </div>
                        <div class="view-mail">
                            <p>
                                {{info.message | linebreaksbr}}
                            </p>
                        </div>
                        <div class="attachment-mail">
                            <p>
                                <span>
                                    — </span> |
                                <a href="{% url 'admins:inbox' %}">View all images</a>
                            </p>
                        </div>
                        <div class="replyBox m-t-20">
                            <p class="p-b-20">click here to
                                <a href="mailto:{{info.email}}">Reply</a>
                                <!-- or
                                <a href="#">Forward</a> -->
                            </p>
                        </div>
                    </section>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}